### ISSUE TITLE
No JAAS configuration section named 'Client' was found 

### ISSUE THREAD

**Issue by Bha91** [layonez/kafka-example#1]
got this warning and errors: 
````
WARN SASL configuration failed: javax.security.auth.login.LoginException: No JAAS configuration section named 'Client' was found in specified JAAS configuration file: '/etc/kafka/kafka_server_jaas.conf'. Will continue connection to Zookeeper server without SASL authentication, if Zookeeper server allows it. (org.apache.zookeeper.ClientCnxn)
ERROR [ZooKeeperClient Kafka server] Auth failed. (kafka.zookeeper.ZooKeeperClient)
````

**Comment by layonez** [comment]
Hey, @Bha91 thank you for reporting!

Can you please also share your OS and docker-compose versions as I don’t have troubles on my setup

**Comment by Bha91** [comment]
> Hey, @Bha91 thank you for reporting!
> 
> Can you please also share your OS and docker-compose versions as I don’t have troubles on my setup

ubuntu 18.04, docker-compose version 1.29.2

**Comment by olegtikhonov** [comment]
Hey, the same here. Any updates are so far? Thanks.

**Comment by layonez** [comment]
@olegtikhonov hey, I actually tried to reproduce it on windows and mac and wasn't able to see any problems.

Can you please describe all steps you've done, and at what point you got this error?
I can only suspect something is wrong with a path to  JAAS configuration, as you can actually find there section named 'Client' ant it's intentionally empty.

**Comment by olegtikhonov** [comment]
Hi @layonez. My problem solved by adding jaws config into Spring Boot app application.yaml.
`
spring:
   kafka:
      properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${kafka_username:'admin'} password=${kafka_password:'admin-secret'};
        mechanism: PLAIN
      security:
        protocol: SASL_PLAINTEXT
`
